### ISSUE TITLE
透明代理设置失败

### ISSUE THREAD

**Issue by aoleou** [dnomd343/XProxy#5]
首先,感谢大神为网络自由做出这么优秀的产品,
然后,经过试用以后,可能是我的姿势不对,没有连接外网. 现在麻烦一下大神,有空的话,帮我看下下面的需求,配合Xproxy如何操作了. 为了实现这个透明代理, 操劳了很多天了.

具体需求为：, **就是2台电脑A和B. 我想让B中的容器Xproxy代理A所有流量,然后 [B中的容器Xproxy或者B中的容器里的xray] 能实现智能代理,国内走够内,国外走国外** . 现在遇到的问题是：
1 流量到B就卡住了,貌似遇到了回环问题.
2 B 分流不够丝滑和智能（这一点，我觉得，做得比较合我心意的是clash的按照域名或者域名中的关键词就实现了分流）

为了实现上面的的需求，我做了以下尝试：
环境：
路由器: ip:　192.168.0.１
电脑A：windows， ip： 192.168.0.66；
电脑B：linux， ip： 192.168.0.67;
电脑B中启动起来的XProxy容器：系统: linux. 网卡: eth0.   ip： 172.18.0.2 (这个ip是容器启动时系统分配的);
电脑C(服务器):vps ip: myvpsip

然后 `/etc/route` 下的内容为:

```txt
.
├── assets
│   ├── geoip.dat
│   └── geosite.dat
├── config
│   ├── outbounds.json
│   └── routing.json
├── log
│   ├── access.log
│   ├── error.log
│   ├── radvd.log
│   └── xproxy.log
└── xproxy.yml
```

其中 `xproxy.yml`内容为
```yml
proxy:
  log: info
  socks:
    proxy4: 1094
    direct4: 1084
    proxy6: 1096
    direct6: 1086
  sniff:
    enable: true
    redirect: true

network:
  dev: ens35  # 对了这里是写宿主机网卡吗?
  dns:
    - 192.168.0.1
  ipv4:
    gateway: 192.168.0.1
    address: 192.168.0.67/24
  ipv6:
    gateway: fe80::1
    address: 2409:8a55:e2a7:3a0::/64
  bypass:
    - 169.254.0.0/16
    - 224.0.0.0/3
    - fc00::/7
    - fe80::/10
    - ff00::/8

radvd:
  log: 3
  dev: ens35 # 对了这里是写宿主机网卡吗?
  enable: true
  option:
    AdvSendAdvert: on
    AdvManagedFlag: off
    AdvOtherConfigFlag: off
  prefix:
    cidr: 2409:8a55:e2a7:3a0::/64

asset:
  update:
    cron: "0 5 6 * * *"
    proxy: "socks5://192.168.0.67:1094"  # 通过代理下载 Github 文件
    url:
      geoip.dat: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
      geosite.dat: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
```

其中 `outbounds.json`内容为
```json
{
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "mydomian",
            "port": 443,
            "users": [
              {
                "id": "myid",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                "flow": "xtls-rprx-vision"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "serverName": "music.google.com",
          "fingerprint": "chrome",
          "show": false,
          "publicKey": "mypublicKey",
          "shortId": "",
          "spiderX": "/"
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ]
}
```

其中 `routing.json`内容为
```json
{
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "inboundTag": ["direct4"],
        "outboundTag": "direct4"
      },
      {
        "type": "field",
        "inboundTag": ["direct6"],
        "outboundTag": "direct6"
      },
      {
        "type": "field",
        "inboundTag": ["proxy4"],
        "outboundTag": "proxy4"
      },
      {
        "type": "field",
        "inboundTag": ["proxy6"],
        "outboundTag": "proxy6"
      },
      {
        "type": "field",
        "inboundTag": ["tproxy4"],
        "domain": ["geosite:cn"],
        "outboundTag": "direct4"
      },
      {
        "type": "field",
        "inboundTag": ["tproxy6"],
        "domain": ["geosite:cn"],
        "outboundTag": "direct6"
      },
      {
        "type": "field",
        "inboundTag": ["tproxy4"],
        "ip": [
          "geoip:cn",
          "geoip:private"
        ],
        "outboundTag": "direct4"
      },
      {
        "type": "field",
        "inboundTag": ["tproxy6"],
        "ip": [
          "geoip:cn",
          "geoip:private"
        ],
        "outboundTag": "direct6"
      },
      {
        "type": "field",
        "inboundTag": ["tproxy4"],
        "outboundTag": "proxy4"
      },
      {
        "type": "field",
        "inboundTag": ["tproxy6"],
        "outboundTag": "proxy6"
      }
    ]
  }
}
```

最终操作及测试:

操作：
```sh
# 以下命令是在电脑B上执行
$ ip link set ens35 promisc on
$ modprobe ip6table_filter
$ docker network create -d macvlan --subnet=fe80::/10 --ipv6 -o parent=ens35 macvlan
$ docker pull dnomd343/xproxy:latest
$ docker run --restart always \
    --privileged --network macvlan -dt \
    --name route --hostname route \
    --volume /etc/route/:/xproxy/ \
    --volume /etc/timezone:/etc/timezone:ro \
    --volume /etc/localtime:/etc/localtime:ro \
    dnomd343/xproxy:latest
```
测试操作:　将windows电脑A: wlan属性--ip和dns 换为B的ip，网络不通．麻烦大神指点一下是哪里出了问题了，非常感谢

**Comment by dnomd343** [comment]
> 路由器: ip:　192.168.0.１
> 电脑A：windows， ip： 192.168.0.66；
> 电脑B：linux， ip： 192.168.0.67;
> 电脑B中启动起来的XProxy容器：系统: linux. 网卡: eth0. ip： 172.18.0.2 (这个ip是容器启动时系统分配的);
> 电脑C(服务器):vps ip: myvpsip

这里的容器IP不对，你在容器内执行 `ip addr` 命令，查看一下输出信息，预期应该是存在lo网卡和ens35网卡，后者IP为你的设置的 `192.168.0.67/24`。

```yaml
network:
  dev: ens35  # 对了这里是写宿主机网卡吗?
  dns:
    - 192.168.0.1
  ipv4:
    gateway: 192.168.0.1
    address: 192.168.0.67/24
  ipv6:
    gateway: fe80::1
    address: 2409:8a55:e2a7:3a0::/64
```

同时，这里的IPv4地址不是你的B主机，是一个完全独立的内网IP地址，确保不和路由器 `192.168.0.1` 或其他设备重叠就行，例如 `192.168.0.2/24` ，IPv6同理。应当存在类似于以下输出才正常。

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
12: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:c0:a8:02:01 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.2/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fc00::2/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c0ff:fea8:201/64 scope link
       valid_lft forever preferred_lft forever
```

如果符合预期，在内网执行 `ping 192.168.0.2` 命令，确认网络是否可达。

此外，使用时不是换你的Windows电脑IP，换的应该是网关地址，你可以手动配置WLAN选项或在路由器配置DHCP选项，网关地址为 `192.168.0.2` 。

**Comment by aoleou** [comment]
首先,[手动抱拳].jpg  非常感谢大神详细的回复. 问题终于解决了,

结合你的指点, 我进行了下面的操作:

1. 把
```sh
$ docker network create -d macvlan --subnet=fe80::/10 --ipv6 -o parent=ens35 macvlan
$ docker run --restart always \
    --privileged --network macvlan -dt \
    --name route --hostname route \
    --volume /etc/route/:/xproxy/ \
    --volume /etc/timezone:/etc/timezone:ro \
    --volume /etc/localtime:/etc/localtime:ro \
    dnomd343/xproxy:latest
```
更换为了
```sh
# 这样使用这个网卡的容器的ip就可以在指定的子网里面指定了. 不然在Alpine Linux里面设置静态ip太麻烦了
docker network create --subnet=192.168.0.0/24 --ipv6 --subnet=fe80:0:0:0:0:0:0:0/64 macvlan

$ docker run --restart always \
>                               --privileged --network macvlan -dt \
>                               --name route --hostname route \
>                               --volume /etc/route/:/xproxy/ \
>                               --volume /etc/timezone:/etc/timezone:ro \
>                               --volume /etc/localtime:/etc/localtime:ro \
>                               --ip 192.168.0.2 \
>                               xproxy:1
```

2. 把测试操作更换为: 将windows电脑A: wlan属性--~~ip~~ 网关和dns 换为B的ip


最后,感谢大神帮忙解决问题, 非常感谢

**Comment by dnomd343** [comment]
在 XProxy 的配置文件，`network` 选项可以配置 Alpine 的静态IP信息的，例如下面的配置，就是指定 IPv4 地址为 `192.168.0.2/24` ，上游网关为 `192.168.0.1` ，由于给了 `privileged` 权限，容器的网络配置是允许被更改的，和 docker 创建命令中指定的地址可以不同，会被强制改过去。

```
network:
  dev: ens35
  dns:
    - 192.168.0.1
  ipv4:
    gateway: 192.168.0.1
    address: 192.168.0.2/24
  ipv6:
    gateway: ...
    address: ...
  bypass:
    - 169.254.0.0/16
    - 224.0.0.0/3
    - fc00::/7
    - fe80::/10
    - ff00::/8
```
